# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jcummins <jcummins@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/28 11:38:00 by jcummins          #+#    #+#              #
#    Updated: 2024/11/07 19:10:57 by jcummins         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${WP_NAME}
        DB_USER: ${WP_USER}
        DB_PASS: ${WP_PASS}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: bind

networks:
  inception:
    driver: bridge

