# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jcummins <jcummins@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/28 11:38:00 by jcummins          #+#    #+#              #
#    Updated: 2024/11/15 18:48:04 by jcummins         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wordpress_data:/var/www/
    networks:
      - docker-network
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    hostname: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/
    networks:
      - docker-network
    restart: always

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  docker-network:
    driver: bridge
