# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jcummins <jcummins@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/28 11:38:00 by jcummins          #+#    #+#              #
#    Updated: 2024/11/10 17:08:51 by jcummins         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    hostname: inception_nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    hostname: inception_mdb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    hostname: inception_wp
    env_file:
      - .env
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/${USER}/data/wordpress
      o: bind
      type: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      o: bind
      type: bind

networks:
  inception:
    driver: bridge

